name: CI
on:
    pull_request:
        branches: [ main ]
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning repo into VM
              uses: actions/checkout@v2.3.4

            - name: Use NodeJS
              uses: actions/setup-node@v1
              with:
                  node-version: "18.x"
            - name: Install
              run: npm install
                

            - name: Run Tests
              run: npm test -- --coverage
              env:
                CI: true

            
            - name: Build Project
              if: github.event_name == 'push'
              run: npm run build
              #create a build when merge
